name: MariaDB Operator
description: MariaDB is an open source relational database management system (DBMS) that is a compatible drop-in replacement for the widely used MySQL database technology.MariaDB is based on SQL and supports ACID-style data processing with guaranteed atomicity, consistency, isolation and durability for transactions.
logo: mariadb-logo.jpeg
bannerimage: Background.png
license: MIT
duration: 1 Minute
documentation: https://www.google.com
categories:
    - Database
intro: intro.md
commands:
    - description: Install Operator
      exec: kubectl create -f https://operatorhub.io/install/mariadb-operator-app.yaml
environment:
    terminal: true
    showide: true
    showdashboard: true
    dashboards:
        - name: Placeholder Tab
          url: '##DNS.host##/app'
    tab_1:
        - name: Overview
backend:
    credits:
        program: prg-name
        unitsPerHour: 10
    services:
        - ibm
          - openshift
        - aws
          - rds
tileInfo:
    - title: MariaDB Operator installation verification
      description:
          Learn how to verify that the MariaDB Operator has been properly installed
          in the namespace.
      duration: 10 min
      content: operator-status.md
    - title: MariaDB Instance creation
      description: Learn how to create Instance of MariaDB operator
      duration: 10 min
      content: create-instance.md
